-- Sample Insurance AI Copilot context documents.
-- Run after 017_genai_context_layer_pgvector.sql.
--
-- Embeddings are intentionally left null. Run the Python embedding pipeline
-- after inserting these documents.

insert into public.semantic_documents (
  document_type,
  source_schema,
  source_table,
  source_column,
  title,
  business_domain,
  content,
  related_tables,
  related_columns,
  related_models,
  related_metrics,
  example_questions,
  sql_examples,
  tags,
  content_hash,
  embedding_model,
  embedding,
  active_flag
)
values
(
  'business_context',
  'public',
  'customers',
  null,
  'Customer 360 Context',
  'customer',
  'Customer 360 combines customer profile, party contact preference, active policies, open opportunities, complaints, service requests, engagement events, model scores, and next-best-actions. Use customers as the customer master and join parties for contact details. Prefer active policies where policy_status is active, issued, or renewed. Use v_latest_model_scores for the latest model output by customer.',
  array['customers','parties','policies','opportunities','customer_complaints','customer_service_requests','customer_engagement_events','model_scores','next_best_actions'],
  array['customer_id','party_id','preferred_contact_method','customer_segment','lifecycle_stage','engagement_score','policy_status','opportunity_stage','score_value','score_band'],
  array['propensity_to_buy','customer_churn','customer_lifetime_value','next_best_product'],
  array['active_policy_count','open_opportunity_count','engagement_score','latest_model_score','next_best_action_priority'],
  array['Show customer 360 for high value customers','Which customers have high churn risk and open complaints?'],
  array['select c.customer_id, p.display_name, c.customer_segment, count(pol.policy_id) as active_policies from public.customers c join public.parties p on p.party_id = c.party_id left join public.policies pol on pol.customer_id = c.customer_id and pol.policy_status in (''active'',''issued'',''renewed'') group by c.customer_id, p.display_name, c.customer_segment;'],
  array['customer_360','crm','profile','copilot'],
  md5('Customer 360 Context'),
  'pending',
  null,
  true
),
(
  'model_context',
  'public',
  'policy_lapse_features',
  null,
  'Policy Lapse Risk Context',
  'policy',
  'Policy lapse risk estimates whether an active policy may lapse or cancel in the prediction window. Features include missed payments, complaints, prior claims, premium change, policy tenure, product, agent, and customer. Avoid leakage by using feature rows where training_window_end is on or before snapshot_date and labels are only from future lapse events.',
  array['policy_lapse_features','policies','payments','policy_lapse_events','policy_renewals','model_scores'],
  array['policy_id','customer_id','agent_id','product_id','missed_payment_count_prior','latest_premium_change_pct','target_label','snapshot_date'],
  array['policy_lapse'],
  array['lapse_risk_score','missed_payment_count','premium_change_pct','persistency'],
  array['Which policies have the highest lapse risk?','Which agents own policies likely to lapse?'],
  array['select p.policy_id, p.customer_id, s.score_value as lapse_risk from public.model_scores s join public.policies p on p.policy_id = s.entity_id where s.model_name = ''policy_lapse'' order by s.score_value desc limit 50;'],
  array['lapse','persistency','retention','ml'],
  md5('Policy Lapse Risk Context'),
  'pending',
  null,
  true
),
(
  'model_context',
  'public',
  'propensity_to_buy_features',
  null,
  'Propensity To Buy Context',
  'customer',
  'Propensity to buy predicts how likely a customer is to purchase a new policy or product in the future window. Useful features are engagement score, active policy count, digital events, quote requests, positive campaign responses, complaints, missed payments, and tenure. It is a customer-level model and should be used for prioritizing cross-sell and nurture actions.',
  array['propensity_to_buy_features','customers','customer_digital_events','campaign_responses','payments','model_scores'],
  array['customer_id','engagement_score','digital_events_90d','quote_requests_180d','positive_campaign_responses_prior','score_value','score_band'],
  array['propensity_to_buy'],
  array['propensity_to_buy_score','quote_requests_180d','digital_engagement','conversion_rate'],
  array['Which customers are most likely to buy?','Which high propensity customers have no health policy?'],
  array['select entity_id as customer_id, score_value as propensity_score, score_band from public.model_scores where model_name = ''propensity_to_buy'' order by score_value desc limit 100;'],
  array['propensity','cross_sell','customer','ml'],
  md5('Propensity To Buy Context'),
  'pending',
  null,
  true
),
(
  'model_context',
  'public',
  'next_best_product_features',
  null,
  'Next Best Product Context',
  'product',
  'Next best product ranks customer-product candidates. The feature table has one row per customer and candidate product snapshot, including prior same-product ownership, product digital interest, quote history, campaign responses, and candidate product line of business. Use candidate_product_id as the recommended product when the score is high.',
  array['next_best_product_features','products','customers','policies','quotes','model_scores'],
  array['customer_id','candidate_product_id','candidate_line_of_business','prior_same_product_count','product_digital_interest_count','prior_quote_count'],
  array['next_best_product'],
  array['next_best_product_score','cross_sell_rate','product_interest_count'],
  array['What is the next best product for each customer?','Which customers should receive a health product recommendation?'],
  array['select n.entity_id as customer_id, n.explanation ->> ''snapshot_date'' as snapshot_date, n.score_value from public.model_scores n where n.model_name = ''next_best_product'' order by n.score_value desc limit 100;'],
  array['nbp','product','recommendation','cross_sell'],
  md5('Next Best Product Context'),
  'pending',
  null,
  true
),
(
  'model_context',
  'public',
  'agent_performance_features',
  null,
  'Agent Performance Context',
  'agent',
  'Agent performance combines MAPA-style activity, calls, meetings, quotes, bound policies, new business premium, target attainment, and territory. It supports identifying high-performing agents, declining productivity, coaching needs, and next-best-customer allocation.',
  array['agents','agent_mapa_metrics','agent_calls','agent_meetings','agent_targets','agent_commissions','agent_performance_features','model_scores'],
  array['agent_id','metric_month','leads_count','contacts_count','quotes_count','applications_count','policies_bound_count','new_business_premium','avg_target_attainment_prior'],
  array['agent_performance','agent_attrition','next_best_customer'],
  array['MAPA','new_business_premium','conversion_rate','target_attainment','agent_productivity'],
  array['Which agents have declining MAPA productivity?','Which agents exceeded new business premium targets?'],
  array['select agent_id, metric_month, leads_count, contacts_count, quotes_count, policies_bound_count, new_business_premium from public.agent_mapa_metrics order by metric_month desc;'],
  array['agent','MAPA','performance','sales'],
  md5('Agent Performance Context'),
  'pending',
  null,
  true
),
(
  'metric_context',
  'public',
  'campaign_responses',
  null,
  'Campaign Conversion Context',
  'campaign',
  'Campaign conversion measures targeted customers or leads that converted to quote, opportunity, or policy after campaign exposure. Use campaign_targets for audience denominator and campaign_responses for opened, clicked, quoted, called, and converted responses. conversion_flag and conversion_premium represent direct attribution when available.',
  array['campaigns','campaign_targets','campaign_responses','leads','opportunities','policies'],
  array['campaign_id','campaign_target_id','response_type','conversion_flag','conversion_premium','target_status','selected_at','response_ts'],
  array['campaign_response','lead_conversion'],
  array['campaign_conversion_rate','response_rate','conversion_premium','cost_per_conversion'],
  array['Which campaigns generated the highest policy conversion?','What is campaign response rate by channel?'],
  array['select c.campaign_name, count(distinct ct.campaign_target_id) as targets, count(distinct cr.campaign_response_id) filter (where cr.conversion_flag) as conversions from public.campaigns c join public.campaign_targets ct on ct.campaign_id = c.campaign_id left join public.campaign_responses cr on cr.campaign_target_id = ct.campaign_target_id group by c.campaign_name order by conversions desc;'],
  array['campaign','conversion','marketing','attribution'],
  md5('Campaign Conversion Context'),
  'pending',
  null,
  true
),
(
  'metric_context',
  'public',
  'claims',
  null,
  'Claims Ratio Context',
  'claims',
  'Claims ratio or loss ratio compares incurred claims to earned premium. Incurred claims are paid_amount plus reserve_amount, also available as incurred_amount. Earned premium is in premiums. Join claims to policies by policy_id and premiums to policies by policy_id. Aggregate by product, customer segment, agent, or period depending on question.',
  array['claims','premiums','policies','products','customers'],
  array['claim_id','policy_id','paid_amount','reserve_amount','incurred_amount','earned_premium_amount','transaction_date','loss_date'],
  array['claim_prediction','fraud_detection'],
  array['claims_ratio','loss_ratio','incurred_claims','earned_premium'],
  array['Which customer segments have the highest claim ratio?','What is loss ratio by product?'],
  array['select prod.product_name, sum(cl.incurred_amount) / nullif(sum(pr.earned_premium_amount),0) as loss_ratio from public.policies p join public.products prod on prod.product_id = p.product_id left join public.claims cl on cl.policy_id = p.policy_id left join public.premiums pr on pr.policy_id = p.policy_id group by prod.product_name order by loss_ratio desc nulls last;'],
  array['claims','loss_ratio','premium','analytics'],
  md5('Claims Ratio Context'),
  'pending',
  null,
  true
),
(
  'model_context',
  'public',
  'claim_fraud_indicators',
  null,
  'Fraud Indicators Context',
  'claims',
  'Fraud indicators are claim-level signals raised by rules, models, adjusters, provider networks, external data, or manual review. Use claim_fraud_indicators for indicator type, source, score, severity, and resolution. Fraud detection model scores are claim-level and should drive fraud_review actions for high-risk claims.',
  array['claims','claim_fraud_indicators','claim_assessments','model_scores','next_best_actions'],
  array['claim_id','customer_id','indicator_date','indicator_type','indicator_source','indicator_score','severity','resolved_flag','score_value','score_band'],
  array['fraud_detection'],
  array['fraud_risk_score','indicator_score','fraud_review_rate'],
  array['Which claims have high fraud risk?','Which fraud indicators are most common?'],
  array['select cl.claim_id, ms.score_value as fraud_risk, fi.indicator_type, fi.indicator_score from public.model_scores ms join public.claims cl on cl.claim_id = ms.entity_id left join public.claim_fraud_indicators fi on fi.claim_id = cl.claim_id where ms.model_name = ''fraud_detection'' order by ms.score_value desc limit 100;'],
  array['fraud','claims','risk','investigation'],
  md5('Fraud Indicators Context'),
  'pending',
  null,
  true
),
(
  'model_context',
  'public',
  'customer_lifetime_value_features',
  null,
  'Customer Lifetime Value Context',
  'customer',
  'Customer lifetime value estimates future customer value using prior policy count, earned premium, incurred claims, complaints, tenure, and future written premium labels. High CLV customers should be prioritized for human agent contact, retention, and relationship review.',
  array['customer_lifetime_value_features','customers','policies','premiums','claims','customer_complaints','model_scores'],
  array['customer_id','prior_policy_count','prior_earned_premium','prior_incurred_claims','complaint_count_prior','tenure_days','score_value'],
  array['customer_lifetime_value'],
  array['CLV','future_written_premium','prior_earned_premium','net_value'],
  array['Which customers have the highest lifetime value?','Which high CLV customers also have high churn risk?'],
  array['select entity_id as customer_id, score_value as clv from public.model_scores where model_name = ''customer_lifetime_value'' order by score_value desc limit 100;'],
  array['clv','customer_value','retention','relationship'],
  md5('Customer Lifetime Value Context'),
  'pending',
  null,
  true
),
(
  'decisioning_context',
  'public',
  'next_best_actions',
  null,
  'Next Best Action Context',
  'decisioning',
  'Next best action combines model scores with CRM context and business suppression rules. Sales actions are suppressed when complaints are unresolved. Marketing actions are suppressed when the customer opted out. High lapse or churn risk takes precedence over cross-sell. Renewal within 60 days takes priority. High CLV increases priority for human agent contact.',
  array['next_best_actions','model_scores','v_next_best_action_recommendations','customers','policies','customer_complaints','customer_service_requests'],
  array['customer_id','agent_id','recommended_action','priority_score','action_reason','suggested_message','expiry_date','decision_rule','suppression_reason'],
  array['propensity_to_buy','policy_lapse','customer_churn','next_best_product','campaign_response','customer_lifetime_value','lead_conversion'],
  array['priority_score','NBA','suppression_rate','action_conversion'],
  array['What is the recommended action for this customer?','Why was sales outreach suppressed?'],
  array['select customer_id, agent_id, recommended_action, priority_score, reason, suggested_message from public.v_next_best_action_recommendations order by priority_score desc limit 100;'],
  array['nba','decisioning','copilot','actions'],
  md5('Next Best Action Context'),
  'pending',
  null,
  true
),
(
  'metric_context',
  'public',
  'agent_mapa_metrics',
  null,
  'MAPA Metrics Context',
  'agent',
  'MAPA-style metrics summarize monthly agent activity and outcomes: leads, contacts, quotes, applications, policies bound, new business premium, renewal premium, retained policies, lapsed policies, claims count, and loss ratio. MAPA is used for agent productivity, conversion, coaching, and performance prediction.',
  array['agent_mapa_metrics','agents','agent_calls','agent_meetings','agent_targets'],
  array['agent_id','metric_month','leads_count','contacts_count','quotes_count','applications_count','policies_bound_count','new_business_premium','renewal_premium','retained_policy_count','lapsed_policy_count','loss_ratio'],
  array['agent_performance','agent_attrition'],
  array['MAPA','activity_to_application','quote_to_bind','new_business_premium','persistency'],
  array['Which agents have declining MAPA productivity?','What is quote to bind rate by agent?'],
  array['select agent_id, metric_month, quotes_count, policies_bound_count, policies_bound_count::numeric / nullif(quotes_count,0) as quote_to_bind_rate from public.agent_mapa_metrics order by metric_month desc;'],
  array['MAPA','agent','productivity'],
  md5('MAPA Metrics Context'),
  'pending',
  null,
  true
),
(
  'model_context',
  'public',
  'customer_churn_features',
  null,
  'Churn Risk Context',
  'customer',
  'Customer churn risk predicts whether a customer may lapse, cancel, or become inactive. Inputs include active policy count, missed payments, complaints, NPS, SLA breaches, engagement, and tenure. Churn risk should trigger retention outreach, especially for high CLV customers.',
  array['customer_churn_features','customers','payments','customer_complaints','customer_nps','customer_service_requests','policy_lapse_events','model_scores'],
  array['customer_id','active_policy_count','missed_payments_180d','complaints_365d','avg_nps_prior','sla_breaches_prior','tenure_days','score_value'],
  array['customer_churn'],
  array['churn_risk_score','retention_rate','missed_payment_rate','complaint_rate'],
  array['Which customers have the highest churn risk?','Which high CLV customers are at churn risk?'],
  array['select entity_id as customer_id, score_value as churn_risk, score_band from public.model_scores where model_name = ''customer_churn'' order by score_value desc limit 100;'],
  array['churn','retention','customer','ml'],
  md5('Churn Risk Context'),
  'pending',
  null,
  true
),
(
  'model_context',
  'public',
  'lead_conversion_features',
  null,
  'Lead Conversion Context',
  'sales',
  'Lead conversion predicts whether a lead will become a policy or purchase. Inputs include lead score, customer engagement, calls, meetings, quotes, campaign attribution, agent assignment, and product. Use lead_conversion scores to prioritize immediate follow-up and agent assignment.',
  array['lead_conversion_features','leads','agent_calls','agent_meetings','quotes','campaigns','model_scores','next_best_actions'],
  array['lead_id','customer_id','agent_id','campaign_id','product_id','lead_score','customer_engagement_score','calls_before_snapshot','meetings_before_snapshot','quotes_before_snapshot','score_value'],
  array['lead_conversion'],
  array['lead_conversion_score','quote_rate','application_rate','sales_conversion'],
  array['Which leads should agents call first?','Which campaigns generate high-converting leads?'],
  array['select l.lead_id, l.customer_id, ms.score_value as conversion_score from public.model_scores ms join public.leads l on l.lead_id = ms.entity_id where ms.model_name = ''lead_conversion'' order by ms.score_value desc limit 100;'],
  array['lead','conversion','sales','agent'],
  md5('Lead Conversion Context'),
  'pending',
  null,
  true
)
on conflict (document_type, content_hash, embedding_model) do update
set title = excluded.title,
    business_domain = excluded.business_domain,
    content = excluded.content,
    related_tables = excluded.related_tables,
    related_columns = excluded.related_columns,
    related_models = excluded.related_models,
    related_metrics = excluded.related_metrics,
    example_questions = excluded.example_questions,
    sql_examples = excluded.sql_examples,
    tags = excluded.tags,
    active_flag = true,
    updated_at = now();

select title, document_type, business_domain, related_models, related_metrics
from public.semantic_documents
where embedding_model = 'pending'
  and title in (
    'Customer 360 Context',
    'Policy Lapse Risk Context',
    'Propensity To Buy Context',
    'Next Best Product Context',
    'Agent Performance Context',
    'Campaign Conversion Context',
    'Claims Ratio Context',
    'Fraud Indicators Context',
    'Customer Lifetime Value Context',
    'Next Best Action Context',
    'MAPA Metrics Context',
    'Churn Risk Context',
    'Lead Conversion Context'
  )
order by business_domain, title;
