insert into public.kpi_definitions (
  kpi_name, business_domain, definition, formula, grain, numerator_definition,
  denominator_definition, required_tables, required_columns, valid_filters, example_sql,
  interpretation_guidance
)
values
('Policy conversion rate', 'campaign', 'Share of targeted campaign population that converted to an issued policy.', 'converted responses / campaign targets', 'campaign, channel', 'campaign_responses where conversion_flag = true', 'campaign_targets', array['campaigns','campaign_targets','campaign_responses'], array['campaign_responses.conversion_flag','campaign_targets.campaign_target_id'], array['campaign','channel','segment','date'], 'select campaign_name, count(*) filter (where conversion_flag)::numeric / nullif(count(*),0) from ...', 'Use with target count, response count, conversion count, and premium generated.'),
('Converted premium', 'campaign', 'Premium generated by campaign conversions.', 'sum(campaign_responses.conversion_premium)', 'campaign, channel', 'conversion premium', 'not applicable', array['campaign_responses','campaigns'], array['campaign_responses.conversion_premium'], array['campaign','channel','product'], 'select campaign_name, sum(conversion_premium) from ...', 'Rank campaigns by converted premium before making budget decisions.'),
('Lapse rate', 'policy', 'Share of policies with lapsed status in the selected book.', 'lapsed policies / total policies', 'policy book or segment', 'policies where policy_status = lapsed', 'all policies in scope', array['policies'], array['policies.policy_status','policies.policy_id'], array['product','agent','segment','date'], 'select count(*) filter (where policy_status=''lapsed'')::numeric / nullif(count(*),0) from public.policies', 'Use as a retention workload trigger.'),
('Annual premium', 'portfolio', 'Annualized premium value of selected policies.', 'sum(policies.annual_premium)', 'product, customer, policy, agent', 'annual premium', 'not applicable', array['policies'], array['policies.annual_premium'], array['product','region','status','effective_date'], 'select product_id, sum(annual_premium) from public.policies group by product_id', 'Use for premium concentration and value-at-risk discussion.'),
('MAPA productivity', 'agent', 'Distribution productivity through Meetings, Activities, Proposals, and Applications.', 'meetings + activities + proposals + applications', 'agent-month', 'MAPA activity counts', 'active agents or agent-months', array['agent_mapa_metrics','agents'], array['agent_mapa_metrics.meetings_count','agent_mapa_metrics.proposals_count','agent_mapa_metrics.applications_count'], array['agent','branch','month'], 'select agent_id, sum(meetings_count), sum(proposals_count) from public.agent_mapa_metrics group by agent_id', 'Compare agents to peer clusters before coaching decisions.')
on conflict (kpi_name, business_domain) do update set
  definition = excluded.definition,
  formula = excluded.formula,
  interpretation_guidance = excluded.interpretation_guidance,
  updated_at = now();

insert into public.table_catalog (table_name, subject_area, business_description, grain, primary_key, common_filters, example_questions)
values
('public.customers', 'customer', 'Customer master and segmentation attributes for customer 360 and propensity questions.', 'one row per customer', 'customer_id', array['customer_segment','country','customer_status'], array['Which customers have high CLV?','Which customers should an agent contact?']),
('public.policies', 'policy', 'Policy contract facts including status, product, premium, dates, and ownership.', 'one row per policy', 'policy_id', array['policy_status','product_id','effective_date'], array['What is lapse rate?','What is persistency by product?']),
('public.products', 'product', 'Insurance product and line of business reference table.', 'one row per product', 'product_id', array['line_of_business','product_category'], array['Which products are declining?','What product mix is growing?']),
('public.campaigns', 'campaign', 'Campaign planning metadata such as name, channel, period, product focus, and budget.', 'one row per campaign', 'campaign_id', array['channel','start_date','end_date'], array['Which campaigns performed best?']),
('public.campaign_targets', 'campaign', 'Customers targeted by each campaign.', 'one row per campaign-customer target', 'campaign_target_id', array['campaign_id','customer_id'], array['What segment was targeted?']),
('public.campaign_responses', 'campaign', 'Customer campaign response and conversion outcome facts.', 'one row per response', 'campaign_response_id', array['conversion_flag','response_type'], array['Which campaign converted?']),
('public.model_scores', 'ml', 'Latest model score outputs for customer, policy, agent, lead, claim, and campaign decisioning.', 'one row per scored entity-model-version', 'model_score_id', array['model_name','score_band','entity_type'], array['Which customers have high lapse risk?']),
('public.next_best_actions', 'decisioning', 'Operational recommendations generated by rules and model scores.', 'one row per recommended action', 'next_best_action_id', array['action_status','action_type','due_date'], array['Which customers should I call first?'])
on conflict (table_name) do update set
  business_description = excluded.business_description,
  grain = excluded.grain,
  common_filters = excluded.common_filters,
  example_questions = excluded.example_questions,
  updated_at = now();

insert into public.model_catalog (
  model_name, model_type, business_purpose, entity_type, score_column, score_interpretation,
  source_table, feature_summary, recommended_usage, limitations, example_questions
)
values
('propensity_to_buy', 'classification', 'Estimate likelihood that a customer will buy or cross-sell.', 'customer', 'score', 'Higher score means stronger buying propensity.', 'public.model_scores', 'Engagement, response, income, tenure, product gaps.', 'Use for cross-sell prioritization with suitability checks.', 'Synthetic MVP scores are directional and require production calibration.', array['Which customers should I cross-sell?']),
('policy_lapse', 'classification', 'Estimate likelihood that a policy will lapse.', 'policy', 'score', 'Higher score means greater lapse risk.', 'public.model_scores', 'Missed payments, premium changes, tenure, engagement, complaints.', 'Use for retention calls and renewal prioritization.', 'Do not use alone for adverse customer treatment.', array['Which policies may lapse?']),
('customer_churn', 'classification', 'Estimate likelihood of customer relationship churn.', 'customer', 'score', 'Higher score means greater churn risk.', 'public.model_scores', 'Complaints, service issues, engagement drop, lapse behavior.', 'Use for service recovery and relationship management.', 'Needs complaint resolution status for best quality.', array['Which customers are likely to churn?']),
('campaign_response', 'classification', 'Estimate customer likelihood to respond to a campaign.', 'customer_campaign', 'score', 'Higher score means greater response probability.', 'public.model_scores', 'Past responses, channel preference, segment, product fit.', 'Use for campaign targeting and follow-up sequencing.', 'Must respect marketing opt-out.', array['Which campaign responders should be followed up?']),
('fraud_risk', 'classification', 'Estimate claim fraud review priority.', 'claim', 'score', 'Higher score means greater fraud review priority.', 'public.model_scores', 'Claim amount, claim pattern, documentation, timing.', 'Use to triage manual review, not to deny claims.', 'Requires claim-level evidence and governance.', array['Which claims have high fraud risk?'])
on conflict (model_name) do update set
  business_purpose = excluded.business_purpose,
  recommended_usage = excluded.recommended_usage,
  limitations = excluded.limitations,
  updated_at = now();

insert into public.missing_data_rules (
  question_pattern, missing_data_condition, missing_data_message, suggested_additional_data, fallback_answer_strategy
)
values
('market|competitor', 'No external market share or competitor benchmark table exists.', 'External market and competitor sales data is missing.', 'Add market share, competitor sales, and industry benchmark feeds.', 'Answer using internal policy, premium, campaign, and lapse trends only.'),
('fraud|claim', 'Claim-level fraud indicator data may be sparse or unavailable for the requested slice.', 'Claim or fraud evidence is incomplete for this exact question.', 'Add claim assessment, fraud indicator, investigation status, and SIU outcome data.', 'Return only claim-level rows and block unsupported fraud conclusions.'),
('agent|MAPA|coaching', 'Agent activity and target data must be present for productivity coaching.', 'Agent productivity evidence is incomplete for this exact question.', 'Add agent MAPA, targets, commissions, and movement history for the same period.', 'Publish a partial portfolio proxy only if clearly labelled.'),
('propensity|cross-sell|next best product', 'Model scores and product holdings are required for cross-sell recommendations.', 'Cross-sell evidence is incomplete without model score and active-product gap data.', 'Add latest model_scores, product suitability flags, active policy holdings, and contact preference.', 'Provide only a directional opportunity view.'),
('lapse|churn|retention', 'Policy events, missed payments, complaints, and model scores improve risk explanation.', 'Retention risk explanation is incomplete without behavior and payment evidence.', 'Add missed-payment history, service issues, complaint status, and policy events.', 'Use policy status and premium at risk as a minimum fallback.')
on conflict do nothing;
