#!/usr/bin/env python3
"""Generate semantic_documents records for insurance analytics text-to-SQL."""

from __future__ import annotations

import csv
import hashlib
import json
import uuid
from datetime import datetime, timezone
from pathlib import Path


OUT_DIR = Path("semantic_layer")
OUT_FILE = OUT_DIR / "semantic_documents.csv"
EMBEDDING_MODEL = "text-embedding-3-small"


FIELDS = [
    "semantic_document_id",
    "glossary_id",
    "document_type",
    "source_schema",
    "source_table",
    "source_column",
    "title",
    "content",
    "tags",
    "content_hash",
    "embedding_model",
    "embedding",
    "active_flag",
    "business_domain",
    "related_tables",
    "related_metrics",
    "example_questions",
    "created_at",
    "updated_at",
]


def pg_array(values: list[str]) -> str:
    escaped = [value.replace("\\", "\\\\").replace('"', '\\"') for value in values]
    return "{" + ",".join(f'"{value}"' for value in escaped) + "}"


def doc(
    title: str,
    document_type: str,
    business_domain: str,
    content: str,
    related_tables: list[str],
    related_metrics: list[str] | None = None,
    example_questions: list[str] | None = None,
    source_table: str | None = None,
    source_column: str | None = None,
    tags: list[str] | None = None,
) -> dict:
    related_metrics = related_metrics or []
    example_questions = example_questions or []
    tags = tags or [business_domain, document_type]
    return {
        "semantic_document_id": str(uuid.uuid4()),
        "glossary_id": "",
        "document_type": document_type,
        "business_domain": business_domain,
        "source_schema": "public" if source_table else "",
        "source_table": source_table or "",
        "source_column": source_column or "",
        "title": title,
        "content": content.strip(),
        "tags": pg_array(tags),
        "content_hash": hashlib.sha256(f"{title}\n{content}".encode("utf-8")).hexdigest(),
        "embedding_model": EMBEDDING_MODEL,
        "embedding": "",
        "active_flag": "true",
        "related_tables": pg_array(related_tables),
        "related_metrics": pg_array(related_metrics),
        "example_questions": pg_array(example_questions),
        "created_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "updated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
    }


DOCS = [
    doc(
        "Customer",
        "business_glossary",
        "customer",
        "A customer is the commercial relationship record linked to a party. Use customers for segmentation, lifecycle stage, risk tier, acquisition date, and engagement score. Join customers to parties for names/contact data and to policies for insurance holdings.",
        ["customers", "parties", "policies", "customer_engagement_events"],
        ["customer_count", "engagement_score", "policy_count"],
        ["How many active customers do we have by segment?", "Which customers have high engagement but no active policy?"],
        "customers",
    ),
    doc(
        "Party",
        "business_glossary",
        "customer",
        "A party is a normalized person, household, or organization identity. Customers, agents, agencies, and households all reference parties. Do not count parties as customers unless joined to customers.",
        ["parties", "customers", "agents", "addresses"],
        ["party_count"],
        ["How many organization parties are agencies?", "Show customer names with their lifecycle stage."],
        "parties",
    ),
    doc(
        "Policy",
        "business_glossary",
        "policy",
        "A policy is the insurance contract header. It has customer, agent, product, dates, lifecycle status, payment plan, annual premium, and written premium. One policy may have many coverages, premiums, payments, claims, and engagement events.",
        ["policies", "customers", "agents", "products", "policy_coverages"],
        ["policy_count", "annual_premium", "written_premium"],
        ["What is active policy count by line of business?", "Which policies lapsed last quarter?"],
        "policies",
    ),
    doc(
        "Agent",
        "business_glossary",
        "agent",
        "An agent is a producer or servicing representative. Agents are linked to party records and may belong to an agency party. Use agents for book-of-business, sales, movement, and MAPA performance analytics.",
        ["agents", "parties", "agent_movements", "agent_mapa_metrics", "policies"],
        ["agent_count", "quote_to_bind_rate", "new_business_premium"],
        ["Which agents produced the most new business premium?", "Which agents transferred agencies this year?"],
        "agents",
    ),
    doc(
        "Campaign",
        "business_glossary",
        "campaign",
        "A campaign is a marketing initiative with objective, channel, line-of-business target, start/end dates, and budget. Campaign attribution flows from campaigns to targets, responses, leads, opportunities, and policies.",
        ["campaigns", "campaign_targets", "campaign_responses", "leads", "opportunities", "policies"],
        ["conversion_rate", "conversion_premium", "campaign_roi"],
        ["Which campaigns generated the most converted premium?", "What is conversion rate by campaign channel?"],
        "campaigns",
    ),
    doc(
        "Claim",
        "business_glossary",
        "claims",
        "A claim is an insurance loss record tied to a policy and customer. Claims include loss date, report date, status, cause, paid amount, reserve amount, and flags for litigation or catastrophe.",
        ["claims", "policies", "customers", "products", "premiums"],
        ["claim_count", "paid_amount", "reserve_amount", "incurred_amount", "loss_ratio"],
        ["Show claim frequency by product family.", "What is loss ratio by line of business?"],
        "claims",
    ),
    doc(
        "Written Premium",
        "kpi_definition",
        "premium",
        "Written premium is the premium recorded when new business, renewal, endorsement, cancellation, reinstatement, or audit transactions are written. Use premiums.written_premium_amount for transaction-level analysis. Use policies.written_premium only for policy-header summaries.",
        ["premiums", "policies", "products", "agents"],
        ["written_premium"],
        ["What was written premium by month?", "Which products had the highest written premium?"],
        "premiums",
        "written_premium_amount",
    ),
    doc(
        "Earned Premium",
        "kpi_definition",
        "premium",
        "Earned premium is the portion of premium recognized for coverage already provided. Use sum(premiums.earned_premium_amount). Earned premium is the denominator for loss ratio.",
        ["premiums", "policies", "products"],
        ["earned_premium", "loss_ratio"],
        ["What was earned premium by quarter?", "Show earned premium by product line."],
        "premiums",
        "earned_premium_amount",
    ),
    doc(
        "Loss Ratio",
        "kpi_definition",
        "claims",
        "Loss ratio equals incurred claims divided by earned premium. Incurred claims should be paid_amount plus reserve_amount from claims. Join claims to policies and premiums by policy_id, aggregate both sides to the same grain before division to avoid premium duplication.",
        ["claims", "premiums", "policies", "products"],
        ["loss_ratio", "incurred_amount", "earned_premium"],
        ["What is loss ratio by line of business?", "Which products have loss ratio above 80%?"],
    ),
    doc(
        "Campaign Conversion Rate",
        "kpi_definition",
        "campaign",
        "Campaign conversion rate equals converted responses divided by sent or selected campaign targets. Use campaign_responses.conversion_flag = true for conversions. For channel-level analysis group by campaigns.channel.",
        ["campaigns", "campaign_targets", "campaign_responses"],
        ["conversion_rate", "converted_response_count", "target_count"],
        ["What is campaign conversion rate by channel?", "Which campaign type converts best for health products?"],
    ),
    doc(
        "Quote to Bind Rate",
        "kpi_definition",
        "agent",
        "Quote-to-bind rate equals policies_bound_count divided by quotes_count from agent_mapa_metrics. Use nullif(quotes_count, 0) to avoid divide-by-zero. This is a monthly agent performance KPI.",
        ["agent_mapa_metrics", "agents"],
        ["quote_to_bind_rate", "quotes_count", "policies_bound_count"],
        ["Which agents had the highest quote-to-bind rate last quarter?", "Compare quote-to-bind rate by territory."],
        "agent_mapa_metrics",
    ),
    doc(
        "Persistency",
        "kpi_definition",
        "policy",
        "Persistency measures retention. In MAPA rows use retained_policy_count divided by retained_policy_count plus lapsed_policy_count. In policy tables, renewed policies are retained and lapsed policies are not retained.",
        ["agent_mapa_metrics", "policies"],
        ["persistency_rate", "retained_policy_count", "lapsed_policy_count"],
        ["Which agents have low persistency?", "What is persistency by product family?"],
    ),
    doc(
        "Customer Engagement Score",
        "kpi_definition",
        "customer",
        "Customer engagement score is a synthetic 0 to 100 score stored in customers.engagement_score. It can be analyzed with engagement event counts, campaign interactions, and policy ownership. Higher scores indicate stronger observed engagement.",
        ["customers", "customer_engagement_events", "campaign_responses", "policies"],
        ["engagement_score", "event_count", "conversion_rate"],
        ["Which high-engagement customers do not have active policies?", "Does engagement score correlate with campaign conversion?"],
        "customers",
        "engagement_score",
    ),
    doc(
        "Policy Status",
        "policy_definition",
        "policy",
        "Policy lifecycle status is stored in policies.policy_status. Values include quoted, issued, active, cancelled, expired, renewed, and lapsed. For in-force policy counts, use statuses active, issued, or renewed depending on reporting definition.",
        ["policies"],
        ["active_policy_count", "lapsed_policy_count", "renewed_policy_count"],
        ["How many active policies do we have?", "What was lapse count by month?"],
        "policies",
        "policy_status",
    ),
    doc(
        "Policy Effective Period",
        "policy_definition",
        "policy",
        "Policy effective_date and expiration_date define the contract coverage period. For point-in-time active policies, filter effective_date <= as_of_date and expiration_date > as_of_date and exclude cancelled/lapsed when appropriate.",
        ["policies"],
        ["active_policy_count", "policy_count"],
        ["How many policies were active on 2025-12-31?", "Show in-force premium by quarter."],
        "policies",
    ),
    doc(
        "Policy Coverage",
        "policy_definition",
        "policy",
        "Policy coverages provide coverage-level details such as coverage code, name, limits, deductibles, exposure basis, and exposure value. Join policy_coverages to policies on policy_id. policy_coverages.product_id points to the base product for base coverage or a rider product for rider coverage. Use is_rider and rider_tag for rider attachment analytics.",
        ["policy_coverages", "policies", "products"],
        ["coverage_count", "average_limit", "average_deductible", "rider_attachment_rate"],
        ["What is average coverage limit by product family?", "Which coverages have high deductibles?", "Which policies include outpatient riders?"],
        "policy_coverages",
    ),
    doc(
        "Products Table",
        "table_description",
        "product",
        "products is the product catalog. Grain is one product component version. Base products have product_component_type = 'base'. Rider products have product_component_type = 'rider' and parent_product_id pointing to the base product. Use rider_category for rider analytics.",
        ["products"],
        ["product_count", "written_premium", "loss_ratio", "rider_attachment_rate"],
        ["What is premium by line of business?", "Which rider categories attach most often?", "Which product families have the most claims?"],
        "products",
    ),
    doc(
        "Product Riders",
        "policy_definition",
        "product",
        "Riders are product components that attach to base policies through policy_coverages. In products, riders have product_component_type = 'rider', parent_product_id referencing the base product, and rider_category describing types such as hospital_cash, outpatient, premium_waiver, early_ci, multipay_ci, accident, legacy, or long_term_care.",
        ["products", "policy_coverages", "policies", "premiums"],
        ["rider_count", "rider_attachment_rate", "rider_new_business_premium"],
        ["Which riders attach most often to PRUShield policies?", "What is NBP by rider category?", "Which agents sell the most critical illness riders?"],
        "products",
    ),
    doc(
        "Policy Rider Tag View",
        "table_description",
        "policy",
        "v_policy_rider_tags is a policy-level view for rider attachment. It returns one row per policy with base product, line of business, rider_count, rider_product_codes, rider_tags, has_rider, policy status, dates, annual premium, and written premium. Use it when the user asks whether policies include riders.",
        ["v_policy_rider_tags", "policies", "policy_coverages", "products"],
        ["rider_count", "rider_attachment_rate", "annual_premium", "written_premium"],
        ["Which policies have riders?", "What is rider attachment rate by base product?", "Which base products have the most rider tags?"],
        "v_policy_rider_tags",
    ),
    doc(
        "Policies Table",
        "table_description",
        "policy",
        "policies is the policy contract header. Grain is one policy. Primary joins: customer_id to customers, agent_id to agents, product_id to products, opportunity_id to opportunities, prior_policy_id to previous policies.",
        ["policies", "customers", "agents", "products", "opportunities"],
        ["policy_count", "annual_premium", "written_premium"],
        ["Show policy count by status.", "What is annual premium by agent?"],
        "policies",
    ),
    doc(
        "Premiums Table",
        "table_description",
        "premium",
        "premiums stores transaction and earning records. Grain is one premium transaction period for a policy or coverage. Use transaction_date for written premium timing and premium_period_start/end for earning period analysis.",
        ["premiums", "policies", "policy_coverages"],
        ["written_premium", "earned_premium"],
        ["Show written premium by transaction type.", "What is earned premium by month?"],
        "premiums",
    ),
    doc(
        "Payments Table",
        "table_description",
        "billing",
        "payments stores billing/payment events. Grain is one payment record for a policy/customer. Use payment_status for paid, failed, reversed, refunded, scheduled, and past_due analysis.",
        ["payments", "policies", "customers"],
        ["billed_amount", "paid_amount", "payment_success_rate"],
        ["What is past due amount by segment?", "Show failed payment rate by payment method."],
        "payments",
    ),
    doc(
        "Claims Table",
        "table_description",
        "claims",
        "claims stores claim headers and financials. Grain is one claim. incurred_amount is generated in Postgres as paid_amount plus reserve_amount. Use loss_date for loss timing and report_date for operational reporting.",
        ["claims", "policies", "customers", "policy_coverages"],
        ["claim_count", "paid_amount", "reserve_amount", "incurred_amount"],
        ["Show claims by loss cause.", "What is average incurred claim by line of business?"],
        "claims",
    ),
    doc(
        "Agents Table",
        "table_description",
        "agent",
        "agents stores producer records. Grain is one agent. Join to parties for agent name and agency party name. Use channel, territory_code, status, appointment_date, and termination_date for producer analytics.",
        ["agents", "parties", "agent_movements", "agent_mapa_metrics"],
        ["agent_count", "active_agent_count"],
        ["How many active agents are in each territory?", "Which channels produce the most premium?"],
        "agents",
    ),
    doc(
        "Agent MAPA Metrics Table",
        "table_description",
        "agent",
        "agent_mapa_metrics stores monthly agent activity and production. Grain is one agent per metric_month. Use it for leads, contacts, quotes, applications, bound policies, premium, retention, lapse, claims, and loss ratio.",
        ["agent_mapa_metrics", "agents"],
        ["leads_count", "quotes_count", "quote_to_bind_rate", "new_business_premium", "persistency_rate"],
        ["Rank agents by new business premium.", "Which agents have high activity but low bind rate?"],
        "agent_mapa_metrics",
    ),
    doc(
        "Campaigns Table",
        "table_description",
        "campaign",
        "campaigns stores campaign definitions. Grain is one campaign. Use campaign_type, channel, objective, target_line_of_business, dates, budget, and status for marketing performance analysis.",
        ["campaigns", "campaign_targets", "campaign_responses"],
        ["campaign_count", "campaign_budget", "conversion_rate"],
        ["Show campaign budget by channel.", "Which campaign types had the highest conversion rate?"],
        "campaigns",
    ),
    doc(
        "Campaign Targets Table",
        "table_description",
        "campaign",
        "campaign_targets stores audience membership. Grain is one targeted customer or lead for a campaign. Use target_status to distinguish selected, sent, suppressed, and excluded audiences.",
        ["campaign_targets", "campaigns", "customers", "leads", "agents"],
        ["target_count", "suppression_rate"],
        ["How many customers were targeted by campaign?", "What suppression reasons are most common?"],
        "campaign_targets",
    ),
    doc(
        "Campaign Responses Table",
        "table_description",
        "campaign",
        "campaign_responses stores response and conversion events. Grain is one campaign response event. Use response_type and conversion_flag for delivered, opened, clicked, called, quoted, converted, bounced, unsubscribed, or no response analysis.",
        ["campaign_responses", "campaigns", "campaign_targets", "leads", "opportunities", "policies"],
        ["response_count", "conversion_count", "conversion_premium"],
        ["Which campaign responses converted to policies?", "What is conversion premium by campaign?"],
        "campaign_responses",
    ),
    doc(
        "Leads Table",
        "table_description",
        "sales",
        "leads stores prospective demand before an opportunity. Grain is one lead. Leads may be linked to an existing customer, a party, a campaign, an assigned agent, and a product.",
        ["leads", "customers", "campaigns", "agents", "products"],
        ["lead_count", "qualified_lead_count", "lead_score"],
        ["How many leads were generated by campaign channel?", "Which agents have the most qualified leads?"],
        "leads",
    ),
    doc(
        "Opportunities Table",
        "table_description",
        "sales",
        "opportunities stores sales pipeline records. Grain is one opportunity. Join to leads, customers, agents, campaigns, products, and policies. opportunity_stage captures opened, quoted, application, underwriting, bound, lost, or withdrawn.",
        ["opportunities", "leads", "customers", "agents", "campaigns", "products", "policies"],
        ["opportunity_count", "quoted_premium", "bind_rate"],
        ["What is pipeline value by stage?", "Which campaigns generated bound opportunities?"],
        "opportunities",
    ),
    doc(
        "Customer Engagement Events Table",
        "table_description",
        "customer",
        "customer_engagement_events stores timestamped interactions. Grain is one event. Events may link to customer, policy, claim, campaign, and agent. Use channel, event_type, sentiment_score, and metadata for engagement analytics.",
        ["customer_engagement_events", "customers", "policies", "claims", "campaigns", "agents"],
        ["event_count", "average_sentiment", "engagement_score"],
        ["What engagement channels are most common?", "Do campaign clicks lead to quote requests?"],
        "customer_engagement_events",
    ),
    doc(
        "Customer to Party Join",
        "join_path",
        "customer",
        "Join customers.party_id = parties.party_id to retrieve customer name, email, phone, and party attributes. Do not join parties directly to policies when counting customers; always go through customers.",
        ["customers", "parties"],
        ["customer_count"],
        ["Show customer names and engagement scores."],
    ),
    doc(
        "Customer to Address Join",
        "join_path",
        "customer",
        "Join customers.party_id = addresses.party_id for customer geography. Filter addresses.is_current = true for current geography. Use address_type = 'primary' for residential/customer location analytics.",
        ["customers", "addresses"],
        ["customer_count"],
        ["How many customers are in Singapore vs Hong Kong?", "Show active customers by district/state code."],
    ),
    doc(
        "Policy Performance Join",
        "join_path",
        "policy",
        "For policy performance, join policies to customers on customer_id, agents on agent_id, and products on product_id. This gives customer segment, agent territory/channel, and line of business for policy counts and premium.",
        ["policies", "customers", "agents", "products"],
        ["policy_count", "annual_premium", "written_premium"],
        ["What is annual premium by product and agent channel?"],
    ),
    doc(
        "Premium to Policy Join",
        "join_path",
        "premium",
        "Join premiums.policy_id = policies.policy_id. For product or agent breakdown, continue from policies to products or agents. Do not join premiums to claims at raw row level when calculating loss ratio; aggregate first.",
        ["premiums", "policies", "products", "agents"],
        ["written_premium", "earned_premium"],
        ["Show earned premium by product family."],
    ),
    doc(
        "Claims to Premium Loss Ratio Join",
        "join_path",
        "claims",
        "To calculate loss ratio, aggregate claims by policy_id and period, aggregate earned premium by policy_id and the same period, then join the aggregates. Joining raw claims to raw premiums can duplicate premium rows.",
        ["claims", "premiums", "policies", "products"],
        ["loss_ratio", "incurred_amount", "earned_premium"],
        ["What is monthly loss ratio by line of business?"],
    ),
    doc(
        "Campaign Attribution Join",
        "join_path",
        "campaign",
        "Campaign attribution path is campaigns -> campaign_targets -> campaign_responses -> leads -> opportunities -> policies. campaign_responses may also directly reference policy_id for conversions. Prefer direct policy_id when present.",
        ["campaigns", "campaign_targets", "campaign_responses", "leads", "opportunities", "policies"],
        ["conversion_rate", "conversion_premium"],
        ["Which campaigns generated policies?", "What is converted premium by campaign?"],
    ),
    doc(
        "Agent Movement Impact Join",
        "join_path",
        "agent",
        "Join agent_movements to agents on agent_id. To study impact, compare MAPA metrics before and after movement.effective_date. Use metric_month before/after the movement month and group by movement_type.",
        ["agent_movements", "agents", "agent_mapa_metrics"],
        ["new_business_premium", "quote_to_bind_rate", "persistency_rate"],
        ["Did transferred agents improve after movement?", "How did agency changes affect lapse rates?"],
    ),
    doc(
        "Written Premium Calculation",
        "metric_rule",
        "premium",
        "Use sum(premiums.written_premium_amount) as written_premium. Filter transaction_date for reporting period. Include negative endorsements/cancellations when measuring net written premium; exclude them only when the user asks for gross written premium.",
        ["premiums"],
        ["written_premium", "net_written_premium", "gross_written_premium"],
        ["What is net written premium by month?", "What is gross new business premium?"],
    ),
    doc(
        "New Business Premium by Rider",
        "metric_rule",
        "premium",
        "For rider-tagged NBP, use public.v_new_business_premium_by_rider. It allocates premiums to base products and rider components from premiums.policy_coverage_id joined to policy_coverages.product_id. The view already filters transaction_type = 'new_business'. Group by rider_tag, component_product_code, base_product_code, agent_id, or transaction_month as needed.",
        ["v_new_business_premium_by_rider", "premiums", "policy_coverages", "products", "policies"],
        ["new_business_premium", "rider_new_business_premium", "base_new_business_premium"],
        ["What is NBP by rider category?", "Which agents generated the most rider NBP?", "What share of NBP came from riders vs base policies?"],
    ),
    doc(
        "Loss Ratio Calculation",
        "metric_rule",
        "claims",
        "Use sum(claims.paid_amount + claims.reserve_amount) / nullif(sum(premiums.earned_premium_amount), 0). Aggregate claims and premium at the requested grain before joining. Format as percentage for UI display.",
        ["claims", "premiums", "policies"],
        ["loss_ratio", "incurred_amount", "earned_premium"],
        ["Show loss ratio by product family.", "Which line has the highest loss ratio?"],
    ),
    doc(
        "Campaign ROI Calculation",
        "metric_rule",
        "campaign",
        "Campaign ROI proxy equals conversion_premium minus budget_amount divided by budget_amount. Use sum(campaign_responses.conversion_premium) and campaigns.budget_amount. This is a synthetic marketing ROI proxy, not IFRS profit.",
        ["campaigns", "campaign_responses"],
        ["campaign_roi", "conversion_premium", "budget_amount"],
        ["Which campaigns had the best ROI?", "Show ROI by campaign channel."],
    ),
    doc(
        "Policy In Force Calculation",
        "metric_rule",
        "policy",
        "A policy is in force on an as-of date when effective_date <= as_of_date, expiration_date > as_of_date, and policy_status in ('active','issued','renewed'). Exclude cancelled and lapsed unless explicitly requested.",
        ["policies"],
        ["in_force_policy_count", "active_policy_count"],
        ["How many policies were in force at year end?"],
    ),
    doc(
        "Sample SQL: Written Premium by Month",
        "sql_template",
        "premium",
        "select date_trunc('month', transaction_date)::date as month, sum(written_premium_amount) as written_premium from public.premiums group by 1 order by 1;",
        ["premiums"],
        ["written_premium"],
        ["What was written premium by month?"],
    ),
    doc(
        "Sample SQL: NBP by Rider Category",
        "sql_template",
        "premium",
        "select rider_tag, is_rider, sum(new_business_premium) as new_business_premium from public.v_new_business_premium_by_rider group by rider_tag, is_rider order by new_business_premium desc;",
        ["v_new_business_premium_by_rider"],
        ["new_business_premium", "rider_new_business_premium"],
        ["What is new business premium by rider category?", "Which riders drive the most NBP?"],
    ),
    doc(
        "Sample SQL: Loss Ratio by Line of Business",
        "sql_template",
        "claims",
        "with claim_agg as (select p.product_id, sum(c.paid_amount + c.reserve_amount) incurred from public.claims c join public.policies p on p.policy_id = c.policy_id group by 1), premium_agg as (select p.product_id, sum(pr.earned_premium_amount) earned from public.premiums pr join public.policies p on p.policy_id = pr.policy_id group by 1) select prod.line_of_business, sum(claim_agg.incurred) / nullif(sum(premium_agg.earned), 0) as loss_ratio from public.products prod left join claim_agg on claim_agg.product_id = prod.product_id left join premium_agg on premium_agg.product_id = prod.product_id group by prod.line_of_business;",
        ["claims", "premiums", "policies", "products"],
        ["loss_ratio", "incurred_amount", "earned_premium"],
        ["Show loss ratio by line of business."],
    ),
    doc(
        "Sample SQL: Campaign Conversion Rate",
        "sql_template",
        "campaign",
        "select c.campaign_name, c.channel, count(*) filter (where cr.conversion_flag) as conversions, count(*) as responses, count(*) filter (where cr.conversion_flag)::numeric / nullif(count(*), 0) as conversion_rate from public.campaigns c join public.campaign_responses cr on cr.campaign_id = c.campaign_id group by c.campaign_name, c.channel order by conversion_rate desc;",
        ["campaigns", "campaign_responses"],
        ["conversion_rate", "conversion_count", "response_count"],
        ["Which campaigns converted best?"],
    ),
    doc(
        "Sample SQL: Agent Quote to Bind",
        "sql_template",
        "agent",
        "select a.agent_number, sum(m.policies_bound_count)::numeric / nullif(sum(m.quotes_count), 0) as quote_to_bind_rate, sum(m.new_business_premium) as new_business_premium from public.agent_mapa_metrics m join public.agents a on a.agent_id = m.agent_id group by a.agent_number order by quote_to_bind_rate desc nulls last;",
        ["agent_mapa_metrics", "agents"],
        ["quote_to_bind_rate", "new_business_premium"],
        ["Which agents have the best quote-to-bind rate?"],
    ),
    doc(
        "Sample SQL: High Engagement Without Active Policy",
        "sql_template",
        "customer",
        "select c.customer_number, c.customer_segment, c.engagement_score from public.customers c where c.engagement_score >= 80 and not exists (select 1 from public.policies p where p.customer_id = c.customer_id and p.policy_status in ('active','issued','renewed')) order by c.engagement_score desc;",
        ["customers", "policies"],
        ["engagement_score", "active_policy_count"],
        ["Which high-engagement customers have no active policy?"],
    ),
    doc(
        "Agent Performance Tier",
        "agent_definition",
        "agent",
        "Agent performance tier can be derived from monthly MAPA metrics. High performers have above-median new business premium, healthy quote-to-bind rate, and acceptable persistency. Low performers may have high activity but low bound policy count or high lapse count.",
        ["agents", "agent_mapa_metrics"],
        ["new_business_premium", "quote_to_bind_rate", "persistency_rate", "lapse_rate"],
        ["Which agents have high activity but poor conversion?", "Which agents are high performers?"],
    ),
    doc(
        "Agent Movement",
        "agent_definition",
        "agent",
        "Agent movements represent appointments, transfers, territory changes, agency changes, terminations, and reactivations. Use effective_date for temporal comparisons and movement_type for grouping.",
        ["agent_movements", "agents", "agent_mapa_metrics"],
        ["agent_count", "new_business_premium", "persistency_rate"],
        ["What happened to production after agency changes?", "How many agents transferred territories?"],
        "agent_movements",
    ),
    doc(
        "Campaign Response Funnel",
        "campaign_definition",
        "campaign",
        "Campaign response funnel order is delivered, opened, clicked/called, quoted, converted. Not every channel has every step. Use response_type counts grouped by campaign_id and channel for funnel analysis.",
        ["campaigns", "campaign_responses"],
        ["delivered_count", "opened_count", "clicked_count", "quoted_count", "conversion_count"],
        ["Show campaign funnel by channel.", "Where do email campaigns drop off?"],
    ),
    doc(
        "Campaign Attribution Premium",
        "campaign_definition",
        "campaign",
        "Campaign conversion premium is stored on campaign_responses.conversion_premium when conversion_flag is true. If policy_id is present, policy annual premium can validate or supplement attribution.",
        ["campaign_responses", "policies", "campaigns"],
        ["conversion_premium", "annual_premium"],
        ["Which campaigns drove the most premium?", "Compare attributed premium to policy annual premium."],
    ),
    doc(
        "Customer Segment",
        "customer_segmentation",
        "customer",
        "Customer segment is stored in customers.customer_segment. Synthetic segments include young_professional, family_protection, affluent_wealth, retirement_planner, health_focused, and sme_owner.",
        ["customers", "policies", "campaign_responses"],
        ["customer_count", "conversion_rate", "written_premium"],
        ["Which customer segment has the most policies?", "Which segment converts best from campaigns?"],
        "customers",
        "customer_segment",
    ),
    doc(
        "Risk Tier",
        "customer_segmentation",
        "customer",
        "Risk tier is stored in customers.risk_tier and indicates synthetic underwriting or risk propensity. Values are low, medium, high, and very_high. Use with claims and premium to analyze loss experience.",
        ["customers", "policies", "claims", "premiums"],
        ["loss_ratio", "claim_frequency", "written_premium"],
        ["What is claim frequency by risk tier?", "Do high-risk customers have higher loss ratio?"],
        "customers",
        "risk_tier",
    ),
    doc(
        "Lifecycle Stage",
        "customer_segmentation",
        "customer",
        "Lifecycle stage is stored in customers.lifecycle_stage. Values include prospect, active, inactive, lapsed, and former. Use for retention, reactivation, cross-sell, and campaign targeting questions.",
        ["customers", "campaign_targets", "campaign_responses", "policies"],
        ["customer_count", "conversion_rate", "lapse_rate"],
        ["Which inactive customers responded to campaigns?", "How many lapsed customers converted?"],
        "customers",
        "lifecycle_stage",
    ),
    doc(
        "Column: policies.policy_status",
        "column_description",
        "policy",
        "policies.policy_status is the lifecycle status of the policy. Use it to filter active, renewed, lapsed, cancelled, expired, quoted, or issued policies. For in-force analysis usually include active, issued, and renewed.",
        ["policies"],
        ["active_policy_count", "lapsed_policy_count"],
        ["Count policies by status."],
        "policies",
        "policy_status",
    ),
    doc(
        "Column: products.line_of_business",
        "column_description",
        "product",
        "products.line_of_business is the highest-level product grouping, such as health, life, critical_illness, savings, investment_linked, or wealth. Use it for executive product performance rollups.",
        ["products", "policies"],
        ["written_premium", "loss_ratio", "policy_count"],
        ["Show written premium by line of business."],
        "products",
        "line_of_business",
    ),
    doc(
        "Column: campaigns.channel",
        "column_description",
        "campaign",
        "campaigns.channel is the primary marketing channel, such as email, sms, direct_mail, agent_call, web, app, social, or partner. Use it to compare response rates and conversion rates.",
        ["campaigns", "campaign_responses"],
        ["conversion_rate", "response_count"],
        ["Which channel has the highest conversion rate?"],
        "campaigns",
        "channel",
    ),
    doc(
        "Column: customer_engagement_events.metadata",
        "column_description",
        "customer",
        "customer_engagement_events.metadata is JSONB for additional event attributes and synthetic data quality flags. Query it only when the user asks about metadata, event quality, or custom event attributes.",
        ["customer_engagement_events"],
        ["event_count"],
        ["Which events have duplicate click candidate flags?"],
        "customer_engagement_events",
        "metadata",
    ),
]


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with OUT_FILE.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS, extrasaction="ignore")
        writer.writeheader()
        for row in DOCS:
            writer.writerow(row)

    readme = {
        "file": str(OUT_FILE),
        "records": len(DOCS),
        "purpose": "Semantic retrieval corpus for insurance analytics text-to-SQL.",
        "embedding_note": "embedding is blank; populate with your embedding model after load.",
        "load_after": "Apply 002_semantic_layer_enrichment.sql and 004_product_riders_and_nbp_views.sql first.",
    }
    (OUT_DIR / "semantic_layer_manifest.json").write_text(json.dumps(readme, indent=2), encoding="utf-8")
    print(f"Wrote {len(DOCS)} semantic documents to {OUT_FILE}")


if __name__ == "__main__":
    main()
